name: Publish to NPM

on:
  release:
    type: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{secrets.NPM_AUTH_TOKEN}}
      - name: Upload to coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info
