name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install
        run: npm install
      - name: Run tests
        run: npm test
        env:
          CI: true
          AIRTABLE_KEY: ${{secrets.AIRTABLE_KEY}}
          AIRTABLE_BASE: appwAUmHwnxdZgI6b
          AIRTABLE_TABLE: "test"
          TEST_FIELD: "title"
          TEST_FILTER: "{email} = 'same@test.com'"
          FIND_ID: "rec66Qg32AP25DJwG"
          NEW_RECORD: '{"title": "test-create", "value": 23, "email": "new@test.com"}'
          BAD_NEW_RECORD: '{"title": "test-bad-create", "value": "nope", "email": "new@test.com"}'
          UPDATE_RECORD_ID: "recI2hLAazYN9rTKc"
          UPDATE_RECORD: '{"id": "recI2hLAazYN9rTKc", "title": "test-UPDATED"}'
          UPDATE_RECORD_RESET: '{"id": "recI2hLAazYN9rTKc", "title": "test-update"}'
          BAD_ID_UPDATE_RECORD: '{"id": "recABCDEFGHASDKLa", "title": "test-BAD-ID-UPDATED"}'
          BAD_FIELD_UPDATE_RECORD: '{"id": "recI2hLAazYN9rTKc", "value": "nope"}'
          DESTRUCTIVE_UPDATE_NULL_FIELD: "email"
          DESTRUCTIVE_UPDATE_RECORD_ID: "recuV3ptCt77Kgao2"
          DESTRUCTIVE_UPDATE_RECORD: '{"id": "recuV3ptCt77Kgao2", "title": "test-UPDATED-destructive", "value": 23}'
          DESTRUCTIVE_UPDATE_RECORD_RESET: '{"id": "recuV3ptCt77Kgao2", "title": "test-destructive", "value": 23, "email": "destructive@test.com"}'
          CREATE_DELETE_RECORD: '{"title": "test-to-be-deleted", "value": 42, "email": "sure@test.com"}'
      - name: Upload to coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./reports/coverage/lcov.info
